### PR TITLE
bump version number for http-types

### PR DESCRIPTION
**Pull request by andygill**

### CODE REVIEW

**Comment by RyanGlScott** [comment]
Thanks! The build error is unrelated (see [here](https://github.com/scotty-web/scotty/pull/180)); I'll fix that soon.

**Comment by RyanGlScott** [comment]
I've [bumped](http://hackage.haskell.org/package/wai-middleware-static-0.8.0) the upper version bound on Hackage, so `kansas-comet` should [build](https://travis-ci.org/ku-fpg/kansas-comet/builds/94949134) on Travis now.

**Comment by andygill** [comment]
What did you do here? Is is possible to bump hackage version bounds post-hoc?

**Comment by RyanGlScott** [comment]
Yes, if you go to a package's Hackage page and click on "edit package information" at the bottom, you can click on a release under the "Cabal file metadata" section and modify its `.cabal` file. You can't change the actual code AFAIK, but you can at least modify version bounds without making another release.

**Comment by andygill** [comment]
Useful. So this change what cabal update does/sees then?

**Comment by RyanGlScott** [comment]
Yeah, `cabal` (should) detect whenever metadata from a Hackage package changes and update your `config` file appropriately (I had to restart the Travis build manually in this case for the change to be seen).

**Pull request merged**
